language: generic
sudo: required
dist: trusty

os:
  - linux

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y fpc

script:
  - fpc pmake/pmake.pp 

notifications:
  email:
    on_success: false
    on_failure: change
